name: Build and Deploy Code

on:
  push:
    branches:
      - main
      - staging
      - test
      - dev
  pull_request:
    branches:
      - main
      - staging

jobs:
  job1:
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: root
      DATABASE_NAME: fastapi
      DATABASE_USERNAME: root
      SECRET_KEY: 09d25e094faa2556c818166b7a99f6f0f4c3b88e8d3e7
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Update PIP
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: |
          pip install pytest
          pytest